services:
  unbound:
    image: "mvance/unbound:1.20.0"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    volumes:
      - "./unbound:/opt/unbound/etc/unbound/"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      xray:
        ipv4_address: 10.8.1.4

  xray:
    image: "ghcr.io/xtls/xray-core:1.8.23"
    container_name: xray
    volumes:
      - "./xray:/etc/xray"
    ports:
      - "443:443/tcp"
    restart: unless-stopped
    dns:
      - 10.8.1.3 # pihole
    cap_add:
      - SYS_MODULE
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      xray:
        ipv4_address: 10.8.1.2

  pihole:
    image: "pihole/pihole:2024.07.0"
    depends_on: [ unbound ]
    container_name: pihole
    hostname: pihole
    dns:
      - 10.8.1.4 # unbound
      - 127.0.0.1
    environment:
      # ⚠️ Change the Web UI Password:
      WEBPASSWORD: <PIHOLE_PASSWORD>
      TZ: "Europe/Moscow"
      ServerIP: 10.8.1.3
      DNS1: 10.8.1.4
      DNS2: 10.8.1.4
      CUSTOM_CACHE_SIZE: 0
    volumes:
      - '~/.pihole/etc-pihole:/etc/pihole'
      - './.pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      xray:
        ipv4_address: 10.8.1.3
    cpus: "0.8"

networks:
  xray:
    ipam:
      config:
        - subnet: 10.8.1.0/24
